service: aoc-bot

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  environment:
    AOC_LEADERBOARD_ID: ${env:AOC_LEADERBOARD_ID}
    AOC_SESSION_COOKIE: ${env:AOC_SESSION_COOKIE}
    AOC_YEAR: ${env:AOC_YEAR}
    SLACK_AOC_ADMIN_ID: ${env:SLACK_AOC_ADMIN_ID}
    SLACK_APP_ID: ${env:SLACK_APP_ID}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/aoc-manual-timing
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/aoc-participants

plugins:
  - serverless-plugin-typescript

functions:
  initiateRegistration:
    name: ${sls:stage}-inititate-registration
    handler: src/handler.initiateRegistration
    events:
      - httpApi:
          path: /aoc/initiate-registration
          method: post
  handleInteraction:
    name: ${sls:stage}-handle-interaction
    handler: src/handler.handleInteraction
    events:
      - httpApi:
          path: /aoc/handle-interaction
          method: post
  manualStart:
    name: ${sls:stage}-manual-start
    handler: src/handler.manualStart
    events:
      - httpApi:
          path: /aoc/manual-start
          method: post
  shareLeaderboard:
    name: ${sls:stage}-leaderboard
    handler: src/handler.leaderboard
    events:
      - httpApi:
          path: /aoc/leaderboard
          method: post

resources:
  Resources:
    ParticipantTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: aoc-participants
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        KeySchema: [{ AttributeName: SlackId, KeyType: HASH }]
        AttributeDefinitions: [{ AttributeName: SlackId, AttributeType: "S" }]
    ManualTimingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: aoc-manual-timing
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 1
        KeySchema:
          [
            { AttributeName: DayNumber, KeyType: HASH },
            { AttributeName: AocId, KeyType: RANGE },
          ]
        AttributeDefinitions:
          [
            { AttributeName: DayNumber, AttributeType: "N" },
            { AttributeName: AocId, AttributeType: "S" },
          ]
